//! `CacheStore` constructor, accessors, and manifest helpers.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use super::CacheStore;
use super::io::mtime_of_file;
use super::types::FILES_SUBDIR;
use super::types::{
    CACHE_VERSION, CacheEntry, CacheError, CacheLookup, CacheManifest, MANIFEST_NAME,
};

impl CacheStore {
    /// Open the cache at `cache_dir`, creating the directory layout if
    /// it does not exist. Reads an existing manifest if present;
    /// otherwise starts with an empty manifest. No size limit is enforced.
    pub fn open(cache_dir: PathBuf) -> Result<Self> {
        Self::open_with_capacity(cache_dir, 0)
    }

    /// Open the cache with a maximum on-disk size in MiB. `0` disables
    /// the size limit.
    pub fn open_with_capacity(cache_dir: PathBuf, max_size_mb: u64) -> Result<Self> {
        let files_dir = cache_dir.join(FILES_SUBDIR);
        fs::create_dir_all(&files_dir)
            .with_context(|| format!("creating cache directory {}", files_dir.display()))?;

        let manifest_path = cache_dir.join(MANIFEST_NAME);
        let manifest = if manifest_path.is_file() {
            let bytes = fs::read(&manifest_path)
                .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
            match serde_json::from_slice::<CacheManifest>(&bytes) {
                Ok(m) => {
                    if m.schema_version != CACHE_VERSION {
                        return Err(CacheError::SchemaMismatch {
                            found: m.schema_version,
                            expected: CACHE_VERSION,
                        }
                        .into());
                    }
                    if m.tool_version != env!("CARGO_PKG_VERSION") {
                        // Same major version is fine; a different version
                        // means detector behavior may have shifted.
                        // We still load (so the user can see existing
                        // entries) but flag dirty so stale entries are
                        // overwritten as the scan proceeds.
                        tracing::warn!(
                            cached = %m.tool_version,
                            current = %env!("CARGO_PKG_VERSION"),
                            "cache was generated by a different slopguard version; entries will be rewritten"
                        );
                    }
                    m
                }
                Err(e) => {
                    tracing::warn!(
                        path = %manifest_path.display(),
                        error = %e,
                        "manifest is corrupt; starting with an empty manifest"
                    );
                    Self::empty_manifest(&cache_dir)
                }
            }
        } else {
            Self::empty_manifest(&cache_dir)
        };

        Ok(Self {
            cache_dir,
            files_dir,
            manifest,
            dirty: false,
            max_size_bytes: max_size_mb.saturating_mul(1024 * 1024),
        })
    }

    fn empty_manifest(cache_dir: &Path) -> CacheManifest {
        CacheManifest {
            schema_version: CACHE_VERSION,
            tool_version: env!("CARGO_PKG_VERSION").to_string(),
            cache_dir: cache_dir.display().to_string(),
            files: HashMap::new(),
        }
    }

    /// Path to the cache root.
    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    /// Number of files currently tracked in the manifest.
    pub fn len(&self) -> usize {
        self.manifest.files.len()
    }

    /// True when no entries are tracked.
    pub fn is_empty(&self) -> bool {
        self.manifest.files.is_empty()
    }

    /// Look up an entry by its relative file path. Returns:
    ///
    /// - `Hit(entry)` when the manifest has the file AND the
    ///   `content_hash` matches.
    /// - `Stale` when the file is tracked but the hash is different.
    /// - `Miss` when the file is not in the manifest.
    pub fn lookup(&self, file: &str, content_hash: &str) -> CacheLookup {
        let Some(meta) = self.manifest.files.get(file) else {
            return CacheLookup::Miss;
        };
        if meta.content_hash != content_hash {
            return CacheLookup::Stale;
        }
        // mtime drift is not fatal — the hash is authoritative. We
        // log a warning so a corrupted mtime (e.g. from a touch) is
        // visible.
        if let Ok(actual) = mtime_of_file(file) {
            if actual.0 < meta.mtime_secs
                || (actual.0 == meta.mtime_secs && actual.1 < meta.mtime_nanos)
            {
                tracing::debug!(
                    file,
                    "cache entry mtime is newer than on-disk mtime; serving from cache"
                );
            }
        }
        match self.read_entry(&meta.cache_key) {
            Some(entry) => CacheLookup::Hit(entry),
            None => CacheLookup::Stale,
        }
    }

    /// Cheap pre-check that the manifest has a matching `content_hash`
    /// for `file`. Does not read the per-file entry from disk.
    pub fn is_cache_hit(&self, file: &str, content_hash: &str) -> bool {
        matches!(self.lookup(file, content_hash), CacheLookup::Hit(_))
    }

    /// Read the manifest entry for `file` and load the on-disk
    /// `CacheEntry` for it. Returns `None` when the file is not in the
    /// manifest or the entry file is missing/corrupt.
    pub fn get(&self, file: &str) -> Option<CacheEntry> {
        let meta = self.manifest.files.get(file)?;
        self.read_entry(&meta.cache_key)
    }

    /// Read-only access to the manifest, primarily for tests and
    /// diagnostics output.
    pub fn manifest(&self) -> &CacheManifest {
        &self.manifest
    }

    pub(super) fn read_entry(&self, cache_key: &str) -> Option<CacheEntry> {
        super::store_lifecycle::read_entry(self, cache_key)
    }
}
