//! `CacheStore` constructor, accessors, and manifest helpers.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(test)]
use super::types::CacheEntry;
use super::types::FILES_SUBDIR;
use super::types::{CACHE_VERSION, CacheError, CacheLookup, CacheManifest, MANIFEST_NAME};
use super::{CacheStore, DiskBackend, InMemoryBackend};

impl CacheStore {
    /// Open the cache with a maximum on-disk size in MiB. `0` disables
    /// the size limit.
    #[must_use = "callers must handle cache open failures"]
    pub fn open_with_capacity(cache_dir: PathBuf, max_size_mb: u64) -> Result<Self, CacheError> {
        Self::open_with_limits(cache_dir, max_size_mb, 0.9, 4)
    }

    /// Open the cache with explicit eviction and per-file size settings.
    #[must_use = "callers must handle cache open failures"]
    pub fn open_with_limits(
        cache_dir: PathBuf,
        max_size_mb: u64,
        evict_target_ratio: f64,
        max_file_size_mb: u64,
    ) -> Result<Self, CacheError> {
        let files_dir = cache_dir.join(FILES_SUBDIR);
        fs::create_dir_all(&files_dir)?;

        let manifest_path = cache_dir.join(MANIFEST_NAME);
        let manifest = if manifest_path.is_file() {
            let bytes = fs::read(&manifest_path)?;
            match serde_json::from_slice::<CacheManifest>(&bytes) {
                Ok(m) => {
                    if m.schema_version != CACHE_VERSION {
                        return Err(CacheError::SchemaMismatch {
                            found: m.schema_version,
                            expected: CACHE_VERSION,
                        });
                    }
                    if m.tool_version != env!("CARGO_PKG_VERSION") {
                        // Same major version is fine; a different version
                        // means detector behavior may have shifted.
                        // We still load (so the user can see existing
                        // entries) but flag dirty so stale entries are
                        // overwritten as the scan proceeds.
                        tracing::warn!(
                            cached = %m.tool_version,
                            current = %env!("CARGO_PKG_VERSION"),
                            "cache was generated by a different slopguard version; entries will be rewritten"
                        );
                    }
                    m
                }
                Err(e) => {
                    tracing::warn!(
                        path = %manifest_path.display(),
                        error = %e,
                        "manifest is corrupt; starting with an empty manifest"
                    );
                    Self::empty_manifest()
                }
            }
        } else {
            Self::empty_manifest()
        };

        let evict_target_ratio =
            if evict_target_ratio.is_finite() && (0.1..=0.99).contains(&evict_target_ratio) {
                evict_target_ratio
            } else {
                tracing::warn!(
                    evict_target_ratio,
                    "cache.evict_target_ratio must be between 0.1 and 0.99; falling back to 0.9"
                );
                0.9
            };

        Ok(Self {
            cache_dir,
            files_dir: files_dir.clone(),
            manifest,
            dirty: false,
            max_size_bytes: max_size_mb.saturating_mul(1024 * 1024),
            evict_target_ratio,
            max_file_size_bytes: max_file_size_mb.saturating_mul(1024 * 1024),
            backend: Box::new(DiskBackend { files_dir }),
            ephemeral: false,
        })
    }

    /// Create a purely in-memory cache store. All entries live in a
    /// `HashMap`; no filesystem operations are performed. Useful for
    /// tests and ephemeral use.
    #[must_use = "in-memory cache is useless if discarded"]
    pub fn in_memory() -> Self {
        Self {
            cache_dir: PathBuf::new(),
            files_dir: PathBuf::new(),
            manifest: CacheManifest {
                schema_version: CACHE_VERSION,
                tool_version: env!("CARGO_PKG_VERSION").to_string(),
                files: HashMap::new(),
            },
            dirty: false,
            max_size_bytes: 0,
            evict_target_ratio: 0.9,
            max_file_size_bytes: 0,
            backend: Box::new(InMemoryBackend::new()),
            ephemeral: true,
        }
    }

    fn within_max_file_size(&self, size_bytes: u64) -> bool {
        self.max_file_size_bytes == 0 || size_bytes <= self.max_file_size_bytes
    }

    pub fn should_cache_path(&self, path: &Path) -> bool {
        if self.max_file_size_bytes == 0 {
            return true;
        }
        let Ok(meta) = fs::metadata(path) else {
            return true;
        };
        if self.within_max_file_size(meta.len()) {
            return true;
        }
        tracing::debug!(
            path = %path.display(),
            file_size_mb = meta.len() as f64 / (1024.0 * 1024.0),
            max_file_size_mb = self.max_file_size_bytes as f64 / (1024.0 * 1024.0),
            "skipping cache for file larger than configured max_file_size_mb"
        );
        false
    }

    pub fn should_cache_bytes(&self, size_bytes: u64) -> bool {
        self.within_max_file_size(size_bytes)
    }

    fn empty_manifest() -> CacheManifest {
        CacheManifest {
            schema_version: CACHE_VERSION,
            tool_version: env!("CARGO_PKG_VERSION").to_string(),
            files: HashMap::new(),
        }
    }

    /// Path to the cache root.
    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    /// Number of files currently tracked in the manifest.
    #[cfg(test)]
    pub fn len(&self) -> usize {
        self.manifest.files.len()
    }

    /// True when no entries are tracked.
    #[cfg(test)]
    pub fn is_empty(&self) -> bool {
        self.manifest.files.is_empty()
    }

    /// Look up an entry by its relative file path. Returns:
    ///
    /// - `Hit(entry)` when the manifest has the file AND the
    ///   `content_hash` matches.
    /// - `Stale` when the file is tracked but the hash is different.
    /// - `Miss` when the file is not in the manifest.
    pub fn lookup(&self, file: &str, content_hash: &str) -> CacheLookup {
        let Some(meta) = self.manifest.files.get(file) else {
            return CacheLookup::Miss;
        };
        if meta.content_hash != content_hash {
            return CacheLookup::Stale;
        }
        match self.backend.load_entry(&meta.cache_key) {
            Some(entry) => CacheLookup::Hit(entry),
            None => CacheLookup::Stale,
        }
    }

    /// Cheap pre-check that the manifest has a matching `content_hash`
    /// for `file`. Does not read the per-file entry from disk.
    #[cfg(test)]
    pub fn is_cache_hit(&self, file: &str, content_hash: &str) -> bool {
        matches!(self.lookup(file, content_hash), CacheLookup::Hit(_))
    }

    /// Read the manifest entry for `file` and load the on-disk
    /// `CacheEntry` for it. Returns `None` when the file is not in the
    /// manifest or the entry file is missing/corrupt.
    #[cfg(test)]
    pub fn get(&self, file: &str) -> Option<CacheEntry> {
        let meta = self.manifest.files.get(file)?;
        self.backend.load_entry(&meta.cache_key)
    }

    /// Read-only access to the manifest, primarily for tests and
    /// diagnostics output.
    pub fn manifest(&self) -> &CacheManifest {
        &self.manifest
    }
}
