use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let json_path = PathBuf::from("ruleset/golang/golang.json");
    println!("cargo:rerun-if-changed={}", json_path.display());

    let json_text = fs::read_to_string(&json_path)
        .expect("Failed to read ruleset/golang/golang.json");

    let parsed: serde_json::Value = serde_json::from_str(&json_text)
        .expect("Failed to parse ruleset/golang/golang.json as JSON");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = PathBuf::from(out_dir).join("rule_catalogue.rs");

    let mut code = String::new();
    code.push_str("// This file is auto-generated by build.rs from ruleset/golang/golang.json\n");
    code.push_str("// DO NOT EDIT MANUALLY\n\n");
    code.push_str("use std::sync::LazyLock;\n\n");
    code.push_str("static RULE_CATALOGUE_INNER: LazyLock<Vec<RuleDescription>> = LazyLock::new(|| {\n");
    code.push_str("    vec![\n");

    let obj = parsed
        .as_object()
        .expect("JSON root must be an object");

    for (_key, value) in obj {
        let id_val = value
            .get("id")
            .and_then(|v| v.as_u64().map(|n| n.to_string()).or_else(|| v.as_str().map(String::from)))
            .unwrap_or_default();
        let name = value.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let description = value.get("description").and_then(|v| v.as_str()).unwrap_or("");
        let original_description = value.get("original_description").and_then(|v| v.as_str()).unwrap_or("");
        let category = value.get("category").and_then(|v| v.as_str()).unwrap_or("");
        let detection_notes = value.get("detection_notes").and_then(|v| v.as_str()).unwrap_or("");

        code.push_str(&format!(
            "        RuleDescription {{\n\
             \x20           id: \"{}\".into(),\n\
             \x20           name: \"{}\".into(),\n\
             \x20           description: \"{}\".into(),\n\
             \x20           original_description: \"{}\".into(),\n\
             \x20           category: \"{}\".into(),\n\
             \x20           detection_notes: \"{}\".into(),\n\
             \x20       }},\n",
            escape_rust_string(&id_val),
            escape_rust_string(name),
            escape_rust_string(description),
            escape_rust_string(original_description),
            escape_rust_string(category),
            escape_rust_string(detection_notes),
        ));
    }

    code.push_str("    ]\n");
    code.push_str("});\n\n");
    code.push_str("/// Returns the built-in rule catalogue, compiled at build time from\n");
    code.push_str("/// `ruleset/golang/golang.json` with zero runtime JSON parsing cost.\n");
    code.push_str("pub fn builtin_rule_catalogue() -> &'static [RuleDescription] {\n");
    code.push_str("    &RULE_CATALOGUE_INNER\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).expect("Failed to write rule_catalogue.rs");
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}
