#![cfg(feature = "python")]
mod helpers;

use helpers::baseline::{
    TempProject, parse_findings, run_codehound, save_baseline, setup_temp_project,
};

const BASELINE_FILE: &str = ".codehound-baseline.json";
const SCAN_ARGS: &[&str] = &[
    "--profile",
    "all",
    "--format",
    "json",
    "--no-context",
    "--no-chunks",
    "--lang",
    "python",
];

fn assert_success(output: &std::process::Output) {
    assert!(
        output.status.success(),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn scan_with_args(project: &TempProject, extra_args: &[&str]) -> std::process::Output {
    let mut args = SCAN_ARGS.to_vec();
    args.extend_from_slice(extra_args);
    run_codehound(&args, project.path())
}

#[test]
fn corrupted_baseline_warns_and_scan_proceeds_unfiltered() {
    let project = setup_temp_project(&["sample.py"]);
    project.write_file(BASELINE_FILE, "{not-json");

    let output = scan_with_args(&project, &["--baseline-file", BASELINE_FILE, "sample.py"]);

    assert_eq!(output.status.code(), Some(1));
    let findings = parse_findings(&String::from_utf8_lossy(&output.stdout));
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].rule_id, "SLOP101");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("warning: could not load baseline"),
        "stderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn unsupported_baseline_version_warns_and_skips_filtering() {
    let project = setup_temp_project(&["sample.py"]);
    save_baseline(&project, "sample.py", BASELINE_FILE);

    let baseline_path = project.join(BASELINE_FILE);
    let mut baseline_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&baseline_path).unwrap()).unwrap();
    baseline_json["version"] = serde_json::Value::String("2".to_string());
    std::fs::write(
        &baseline_path,
        format!(
            "{}\n",
            serde_json::to_string_pretty(&baseline_json).unwrap()
        ),
    )
    .unwrap();

    let output = scan_with_args(&project, &["--baseline-file", BASELINE_FILE, "sample.py"]);

    assert_eq!(output.status.code(), Some(1));
    let findings = parse_findings(&String::from_utf8_lossy(&output.stdout));
    assert_eq!(findings.len(), 1);
    assert_eq!(findings[0].rule_id, "SLOP101");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("unsupported version 2"),
        "stderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn older_tool_version_warns_but_still_filters() {
    let project = setup_temp_project(&["sample.py"]);
    save_baseline(&project, "sample.py", BASELINE_FILE);

    let baseline_path = project.join(BASELINE_FILE);
    let mut baseline_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&baseline_path).unwrap()).unwrap();
    baseline_json["tool_version"] = serde_json::Value::String("0.0.0".to_string());
    std::fs::write(
        &baseline_path,
        format!(
            "{}\n",
            serde_json::to_string_pretty(&baseline_json).unwrap()
        ),
    )
    .unwrap();

    let output = scan_with_args(&project, &["--baseline-file", BASELINE_FILE, "sample.py"]);

    assert_success(&output);
    assert_eq!(String::from_utf8_lossy(&output.stdout), "");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("generated by codehound 0.0.0"),
        "stderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn baseline_update_refuses_to_overwrite_corrupt_file() {
    let project = setup_temp_project(&["sample.py"]);
    project.write_file(BASELINE_FILE, "{not-json");
    let before = std::fs::read_to_string(project.join(BASELINE_FILE)).unwrap();

    let output = run_codehound(
        &[
            "--profile",
            "all",
            "--lang",
            "python",
            "baseline",
            "update",
            "--path",
            BASELINE_FILE,
            "sample.py",
        ],
        project.path(),
    );

    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("refusing to replace invalid baseline"),
        "stderr:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        std::fs::read_to_string(project.join(BASELINE_FILE)).unwrap(),
        before,
        "corrupt baseline must remain unchanged"
    );
}
