//! On-disk cache for incremental analysis (P2.3).
//!
//! ## Layout
//!
//! ```text
//! <cache_dir>/
//! ├── manifest.json            # Global index: file -> cache key + metadata
//! ├── files/
//! │   ├── <sha256-of-path-1>.json   # Per-file cache entry (findings, hash, mtime)
//! │   └── ...
//! └── metadata.json            # Tool version + last-scan timestamp
//! ```
//!
//! ## Cache invalidation
//!
//! A cache entry is considered fresh when **all** of the following hold:
//!
//! 1. The manifest has an entry for the file (relative path).
//! 2. The on-disk file's mtime is `>=` the cached mtime.
//! 3. The SHA-256 of the file's current contents matches the cached
//!    `content_hash`.
//! 4. The tool version in the manifest matches the current binary's
//!    `CARGO_PKG_VERSION`.
//!
//! The mtime is the cheap pre-check; the SHA-256 only runs when mtime
//! agrees. This is the same two-stage strategy used by `cargo`, ESLint
//! `--cache`, and Clippy's incremental driver.
//!
//! ## Concurrency
//!
//! `CacheStore` is **not** safe to share across processes or to write
//! to concurrently from multiple threads. The caller is expected to use
//! a single `CacheStore` per scan run and call [`CacheStore::flush`]
//! exactly once at the end. The on-disk format is intended to be
//! overwritten atomically (`tmp` + `rename`); a torn write will be
//! detected on the next `open()` and the affected entry is treated as
//! a miss.

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::rules::Finding;

/// Cache file format version. Bump on any breaking change to the JSON
/// shapes persisted on disk. Older caches are refused on `open()`.
pub const CACHE_VERSION: u32 = 1;

/// Conventional cache directory name. Used when no override is supplied.
pub const DEFAULT_CACHE_DIR: &str = ".slopguard-cache";

/// Cache manifest: cheap O(1) lookup for per-file state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CacheManifest {
    pub schema_version: u32,
    pub tool_version: String,
    pub cache_dir: String,
    pub files: HashMap<String, FileCacheMeta>,
}

/// Per-file metadata stored in the manifest. Mirrors the on-disk entry
/// minus the findings list, so the manifest stays small even for large
/// projects.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileCacheMeta {
    /// Cache key (sha256 of the relative file path, hex).
    pub cache_key: String,
    /// `sha256:<hex>` of the file's source text at scan time.
    pub content_hash: String,
    /// File mtime in seconds since the UNIX epoch.
    pub mtime_secs: u64,
    /// File mtime nanoseconds component.
    pub mtime_nanos: u32,
    /// Resolved language id (`"go"`, `"python"`).
    pub language: String,
    /// Relative file paths this file imports (for transitive
    /// invalidation). Empty when dependency tracking is not enabled.
    #[serde(default)]
    pub dependencies: Vec<String>,
}

/// Full per-file cache entry. Persisted at
/// `<cache_dir>/files/<cache_key>.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CacheEntry {
    pub schema_version: u32,
    pub file: String,
    pub content_hash: String,
    pub mtime_secs: u64,
    pub mtime_nanos: u32,
    pub language: String,
    pub findings: Vec<Finding>,
    #[serde(default)]
    pub dependencies: Vec<String>,
    pub cached_at: String,
}

/// Top-level metadata file (`<cache_dir>/metadata.json`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CacheMetadata {
    pub tool_version: String,
    pub last_scan: String,
    pub entry_count: usize,
}

/// Outcome of a cache lookup.
#[derive(Debug, Clone)]
pub enum CacheLookup {
    /// Fresh entry; findings are returned.
    Hit(CacheEntry),
    /// File is in the manifest but stale (hash or mtime mismatch).
    Stale,
    /// File has no entry in the manifest.
    Miss,
}

/// Errors specific to the cache layer. `CacheStore` never panics on a
/// corrupted entry — it surfaces a [`CacheError::Corrupt`] and the
/// caller can treat the entry as a miss.
#[derive(Debug, thiserror::Error)]
pub enum CacheError {
    #[error("unsupported cache schema version: {found}, expected {expected}")]
    SchemaMismatch { found: u32, expected: u32 },
    #[error("cache was generated by slopguard {found}, current is {current}")]
    ToolVersionMismatch { found: String, current: String },
    #[error("cache entry file missing on disk: {0}")]
    EntryMissing(String),
    #[error("corrupt cache entry: {0}")]
    Corrupt(String),
}

const MANIFEST_NAME: &str = "manifest.json";
const METADATA_NAME: &str = "metadata.json";
const FILES_SUBDIR: &str = "files";

/// Disk-backed cache store. Constructed via [`CacheStore::open`] and
/// used through a single scan run.
pub struct CacheStore {
    cache_dir: PathBuf,
    files_dir: PathBuf,
    manifest: CacheManifest,
    dirty: bool,
}

impl CacheStore {
    /// Open the cache at `cache_dir`, creating the directory layout if
    /// it does not exist. Reads an existing manifest if present;
    /// otherwise starts with an empty manifest.
    pub fn open(cache_dir: PathBuf) -> Result<Self> {
        let files_dir = cache_dir.join(FILES_SUBDIR);
        fs::create_dir_all(&files_dir)
            .with_context(|| format!("creating cache directory {}", files_dir.display()))?;

        let manifest_path = cache_dir.join(MANIFEST_NAME);
        let manifest = if manifest_path.is_file() {
            let bytes = fs::read(&manifest_path)
                .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
            match serde_json::from_slice::<CacheManifest>(&bytes) {
                Ok(m) => {
                    if m.schema_version != CACHE_VERSION {
                        return Err(CacheError::SchemaMismatch {
                            found: m.schema_version,
                            expected: CACHE_VERSION,
                        }
                        .into());
                    }
                    if m.tool_version != env!("CARGO_PKG_VERSION") {
                        // Same major version is fine; a different version
                        // means detector behavior may have shifted.
                        // We still load (so the user can see existing
                        // entries) but flag dirty so stale entries are
                        // overwritten as the scan proceeds.
                        tracing::warn!(
                            cached = %m.tool_version,
                            current = %env!("CARGO_PKG_VERSION"),
                            "cache was generated by a different slopguard version; entries will be rewritten"
                        );
                    }
                    m
                }
                Err(e) => {
                    tracing::warn!(
                        path = %manifest_path.display(),
                        error = %e,
                        "manifest is corrupt; starting with an empty manifest"
                    );
                    Self::empty_manifest(&cache_dir)
                }
            }
        } else {
            Self::empty_manifest(&cache_dir)
        };

        Ok(Self {
            cache_dir,
            files_dir,
            manifest,
            dirty: false,
        })
    }

    fn empty_manifest(cache_dir: &Path) -> CacheManifest {
        CacheManifest {
            schema_version: CACHE_VERSION,
            tool_version: env!("CARGO_PKG_VERSION").to_string(),
            cache_dir: cache_dir.display().to_string(),
            files: HashMap::new(),
        }
    }

    /// Path to the cache root.
    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    /// Number of files currently tracked in the manifest.
    pub fn len(&self) -> usize {
        self.manifest.files.len()
    }

    /// True when no entries are tracked.
    pub fn is_empty(&self) -> bool {
        self.manifest.files.is_empty()
    }

    /// Look up an entry by its relative file path. Returns:
    ///
    /// - `Hit(entry)` when the manifest has the file AND the
    ///   `content_hash` matches.
    /// - `Stale` when the file is tracked but the hash is different.
    /// - `Miss` when the file is not in the manifest.
    pub fn lookup(&self, file: &str, content_hash: &str) -> CacheLookup {
        let Some(meta) = self.manifest.files.get(file) else {
            return CacheLookup::Miss;
        };
        if meta.content_hash != content_hash {
            return CacheLookup::Stale;
        }
        // mtime drift is not fatal — the hash is authoritative. We
        // log a warning so a corrupted mtime (e.g. from a touch) is
        // visible.
        if let Ok(actual) = mtime_of_file(file) {
            if actual.0 < meta.mtime_secs
                || (actual.0 == meta.mtime_secs && actual.1 < meta.mtime_nanos)
            {
                tracing::debug!(
                    file,
                    "cache entry mtime is newer than on-disk mtime; serving from cache"
                );
            }
        }
        match self.read_entry(&meta.cache_key) {
            Some(entry) => CacheLookup::Hit(entry),
            None => CacheLookup::Stale,
        }
    }

    /// Cheap pre-check that the manifest has a matching `content_hash`
    /// for `file`. Does not read the per-file entry from disk.
    pub fn is_cache_hit(&self, file: &str, content_hash: &str) -> bool {
        matches!(self.lookup(file, content_hash), CacheLookup::Hit(_))
    }

    /// Read the manifest entry for `file` and load the on-disk
    /// `CacheEntry` for it. Returns `None` when the file is not in the
    /// manifest or the entry file is missing/corrupt.
    pub fn get(&self, file: &str) -> Option<CacheEntry> {
        let meta = self.manifest.files.get(file)?;
        self.read_entry(&meta.cache_key)
    }

    /// Insert or replace a cache entry. Updates the manifest and marks
    /// the store dirty so [`flush`](Self::flush) writes to disk.
    pub fn put(&mut self, entry: CacheEntry) -> Result<()> {
        let cache_key = cache_key_for_path(&entry.file);
        let entry_path = self.files_dir.join(format!("{cache_key}.json"));
        let meta = FileCacheMeta {
            cache_key: cache_key.clone(),
            content_hash: entry.content_hash.clone(),
            mtime_secs: entry.mtime_secs,
            mtime_nanos: entry.mtime_nanos,
            language: entry.language.clone(),
            dependencies: entry.dependencies.clone(),
        };
        write_atomic(&entry_path, &entry)?;
        self.manifest.files.insert(entry.file.clone(), meta);
        self.dirty = true;
        Ok(())
    }

    /// Remove a single entry from the manifest and from disk. No-op
    /// when `file` is not tracked.
    pub fn remove(&mut self, file: &str) -> Result<()> {
        if let Some(meta) = self.manifest.files.remove(file) {
            let path = self.files_dir.join(format!("{}.json", meta.cache_key));
            if path.is_file() {
                fs::remove_file(&path)
                    .with_context(|| format!("removing cache entry {}", path.display()))?;
            }
            self.dirty = true;
        }
        Ok(())
    }

    /// Drop every entry not present in `scanned_files` from the
    /// manifest and from disk. Use after a scan completes to remove
    /// entries for files that no longer exist.
    pub fn prune(&mut self, scanned_files: &std::collections::HashSet<String>) -> Result<usize> {
        let to_remove: Vec<String> = self
            .manifest
            .files
            .keys()
            .filter(|k| !scanned_files.contains(*k))
            .cloned()
            .collect();
        let count = to_remove.len();
        for file in to_remove {
            self.remove(&file)?;
        }
        Ok(count)
    }

    /// Lazily invalidate the entry for `file`. Equivalent to
    /// [`remove`](Self::remove) but kept as a separate name for use by
    /// callers that invalidate without deleting the on-disk entry
    /// (e.g. when an external observer signals staleness).
    pub fn invalidate_file(&mut self, file: &str) {
        if self.manifest.files.remove(file).is_some() {
            self.dirty = true;
        }
    }

    /// Invalidate every entry whose `dependencies` list contains
    /// `changed_file`. Returns the number of entries invalidated.
    pub fn invalidate_dependent(&mut self, changed_file: &str) -> usize {
        let dependents: Vec<String> = self
            .manifest
            .files
            .iter()
            .filter(|(_, m)| m.dependencies.iter().any(|d| d == changed_file))
            .map(|(k, _)| k.clone())
            .collect();
        let count = dependents.len();
        for d in dependents {
            self.invalidate_file(&d);
        }
        count
    }

    /// Write the manifest and metadata to disk. No-op when no
    /// mutations have happened since the last flush. Should be called
    /// once per scan run, after all `put`/`remove` calls.
    pub fn flush(&mut self) -> Result<()> {
        if !self.dirty {
            return Ok(());
        }
        let manifest_path = self.cache_dir.join(MANIFEST_NAME);
        write_atomic(&manifest_path, &self.manifest)?;
        let metadata = CacheMetadata {
            tool_version: env!("CARGO_PKG_VERSION").to_string(),
            last_scan: iso8601_utc_now(),
            entry_count: self.manifest.files.len(),
        };
        let metadata_path = self.cache_dir.join(METADATA_NAME);
        write_atomic(&metadata_path, &metadata)?;
        self.dirty = false;
        Ok(())
    }

    /// Read-only access to the manifest, primarily for tests and
    /// diagnostics output.
    pub fn manifest(&self) -> &CacheManifest {
        &self.manifest
    }

    fn read_entry(&self, cache_key: &str) -> Option<CacheEntry> {
        let path = self.files_dir.join(format!("{cache_key}.json"));
        if !path.is_file() {
            tracing::warn!(cache_key, "cache entry file missing on disk");
            return None;
        }
        let bytes = match fs::read(&path) {
            Ok(b) => b,
            Err(e) => {
                tracing::warn!(path = %path.display(), error = %e, "failed to read cache entry");
                return None;
            }
        };
        match serde_json::from_slice::<CacheEntry>(&bytes) {
            Ok(e) => {
                if e.schema_version != CACHE_VERSION {
                    tracing::warn!(
                        cache_key,
                        found = e.schema_version,
                        expected = CACHE_VERSION,
                        "cache entry schema mismatch; treating as miss"
                    );
                    return None;
                }
                Some(e)
            }
            Err(err) => {
                tracing::warn!(
                    path = %path.display(),
                    error = %err,
                    "corrupt cache entry; treating as miss"
                );
                None
            }
        }
    }
}

impl Drop for CacheStore {
    fn drop(&mut self) {
        if self.dirty {
            // Best-effort: a `Drop` cannot propagate errors, but we
            // can try to flush so an interrupted scan leaves a
            // consistent cache on disk.
            if let Err(e) = self.flush() {
                tracing::warn!(error = %e, "cache flush on drop failed");
            }
        }
    }
}

/// Compute the SHA-256 of `source` formatted as `sha256:<hex>`.
pub fn content_hash(source: &str) -> String {
    let digest = Sha256::digest(source.as_bytes());
    format!("sha256:{}", hex_lower(&digest))
}

/// Derive a cache-key (filename) for a relative file path: lowercase
/// hex of `Sha256(path.as_bytes())`.
pub fn cache_key_for_path(rel_path: &str) -> String {
    let normalized = rel_path.replace('\\', "/");
    hex_lower(&Sha256::digest(normalized.as_bytes()))
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

/// `(secs, nanos)` from a file's mtime, or `(0, 0)` when the mtime
/// cannot be determined.
fn mtime_of_file(path: &str) -> std::io::Result<(u64, u32)> {
    let meta = fs::metadata(path)?;
    let mtime = meta.modified()?;
    let dur = mtime
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    Ok((dur.as_secs(), dur.subsec_nanos()))
}

fn write_atomic<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let tmp = path.with_extension("json.tmp");
    {
        let mut f = fs::File::create(&tmp)
            .with_context(|| format!("creating tmp file {}", tmp.display()))?;
        let text = serde_json::to_string_pretty(value)
            .with_context(|| format!("serializing {}", path.display()))?;
        f.write_all(text.as_bytes())?;
        f.write_all(b"\n")?;
        f.sync_all().ok();
    }
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Public ISO-8601 timestamp generator used by other engine modules
/// (notably `walk.rs`) when stamping `cached_at` on freshly written
/// cache entries.
pub fn iso8601_now() -> String {
    iso8601_utc_now()
}

fn iso8601_utc_now() -> String {
    let dur = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    let secs = dur.as_secs();
    let (year, month, day, hour, minute, second) = unix_epoch_to_ymdhms(secs);
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

fn unix_epoch_to_ymdhms(secs: u64) -> (u32, u32, u32, u32, u32, u32) {
    let days = secs / 86_400;
    let time_of_day = secs % 86_400;
    let hour = time_of_day / 3600;
    let minute = (time_of_day % 3600) / 60;
    let second = time_of_day % 60;

    let z = days as i64 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (
        y as u32,
        m as u32,
        d as u32,
        hour as u32,
        minute as u32,
        second as u32,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_hash_format_is_stable() {
        let h = content_hash("hello");
        assert!(h.starts_with("sha256:"));
        // SHA-256("hello") = 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
        assert_eq!(
            h,
            "sha256:2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }

    #[test]
    fn cache_key_for_path_is_stable() {
        assert_eq!(
            cache_key_for_path("a/b/c.go"),
            cache_key_for_path("a/b/c.go")
        );
    }

    #[test]
    fn cache_key_normalizes_backslashes() {
        assert_eq!(
            cache_key_for_path("a\\b\\c.go"),
            cache_key_for_path("a/b/c.go")
        );
    }
}
