use super::super::facts::GoUnitFacts;
use super::super::metadata::*;
use crate::core::ParsedUnit;
use crate::rules::{Finding, emit};
pub(crate) fn detect_cwe_325(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    if !source.contains("cipher.NewCTR(") || !source.contains("XORKeyStream(") {
        return;
    }
    if source.contains("cipher.NewGCM(") || source.contains("Seal(") {
        return;
    }

    let start_byte = source.find("cipher.NewCTR(").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_325,
        file,
        line,
        col,
        "sensitive data is encrypted with CTR mode without an authentication or integrity step",
        out,
    );
}

pub(crate) fn detect_cwe_334(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    if !source.contains("Intn(4096)") {
        return;
    }

    let start_byte = source.find("Intn(4096)").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_334,
        file,
        line,
        col,
        "the generated token comes from a very small 4096-value space and is easy to guess",
        out,
    );
}

pub(crate) fn detect_cwe_335(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let predictable_seed = (source.contains("seed := time.Now().Unix()")
        || source.contains("rand.NewSource(seed)"))
        && (source.contains("rand.Seed(seed)")
            || source.contains("rand.New(rand.NewSource(seed))"));
    if !predictable_seed {
        return;
    }

    let start_byte = if let Some(idx) = source.find("time.Now().Unix()") {
        idx
    } else {
        source.find("rand.NewSource(seed)").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_335,
        file,
        line,
        col,
        "the PRNG is seeded from predictable wall-clock time for a security-sensitive ticket value",
        out,
    );
}

pub(crate) fn detect_cwe_338(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let weak_prng_token = (source.contains("rand.New(rand.NewSource(time.Now().UnixNano()))")
        || source.contains("rand.NewSource(time.Now().UnixNano())"))
        && (source.contains("sid") || source.contains("token"));
    if !weak_prng_token {
        return;
    }

    let start_byte =
        if let Some(idx) = source.find("rand.New(rand.NewSource(time.Now().UnixNano()))") {
            idx
        } else {
            source
                .find("rand.NewSource(time.Now().UnixNano())")
                .unwrap_or(0)
        };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_338,
        file,
        line,
        col,
        "a security-sensitive token is generated from math/rand instead of cryptographic randomness",
        out,
    );
}

pub(crate) fn detect_cwe_342(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let increments_previous = (source.contains("lastOTP++") && source.contains("code := lastOTP"))
        || (source.contains("lastSmsCode++") && source.contains("code := lastSmsCode"));
    if !increments_previous {
        return;
    }

    let start_byte = if let Some(idx) = source.find("lastOTP++") {
        idx
    } else {
        source.find("lastSmsCode++").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_342,
        file,
        line,
        col,
        "the next OTP value is generated by incrementing the previous one",
        out,
    );
}

pub(crate) fn detect_cwe_343(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let deterministic_state_machine =
        source.contains("*3 + 1) % 97") || source.contains("*5 + 3) % 101");
    if !deterministic_state_machine {
        return;
    }

    let start_byte = if let Some(idx) = source.find("*3 + 1) % 97") {
        idx
    } else {
        source.find("*5 + 3) % 101").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_343,
        file,
        line,
        col,
        "the output range is produced by a deterministic recurrence over shared state and is predictable from previous values",
        out,
    );
}

pub(crate) fn detect_cwe_347(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let decodes_jwt_payload = source.contains("strings.Split(raw, \".\")")
        && source.contains("DecodeString(parts[1])")
        && source.contains("json.Unmarshal(payload, &claims)");
    if !decodes_jwt_payload {
        return;
    }
    if source.contains("VerifyPKCS1v15(") || source.contains("invalid signature") {
        return;
    }

    let start_byte = source.find("DecodeString(parts[1])").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_347,
        file,
        line,
        col,
        "JWT claims are decoded and trusted without verifying the token signature first",
        out,
    );
}

pub(crate) fn detect_cwe_1204(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let static_iv = source.contains("cipher.NewCBCEncrypter(")
        && (source.contains("weakIV") || source.contains("weakIVPure"))
        && source.contains("1234567890123456");
    if !static_iv {
        return;
    }
    if source.contains("io.ReadFull(rand.Reader, iv)") {
        return;
    }

    let start_byte = source.find("1234567890123456").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_1204,
        file,
        line,
        col,
        "CBC encryption uses a fixed IV literal instead of generating one per request",
        out,
    );
}

pub(crate) fn detect_cwe_1240(unit: &ParsedUnit, _facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let custom_xor_cipher = (source.contains("SealSessionToken(")
        || source.contains("SealSessionTokenPure("))
        && (source.contains("xorCipher(") || source.contains("xorCipherPure("))
        && source.contains("^ key");
    if !custom_xor_cipher {
        return;
    }
    if source.contains("cipher.NewGCM(") || source.contains("aes.NewCipher(") {
        return;
    }

    let start_byte = source.find("xorCipher").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_1240,
        file,
        line,
        col,
        "session sealing uses a homegrown XOR cipher instead of a standard authenticated primitive",
        out,
    );
}
