use super::super::super::facts::GoUnitFacts;
use super::super::super::metadata::*;
use crate::core::ParsedUnit;
use crate::rules::{Finding, emit};
pub(crate) fn detect_cwe_334(unit: &ParsedUnit, facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    // Fixture-only needle (see rules::maturity::FixtureOnly / CWE-334 quarantine).
    // Keep detector for --profile all corpus tests; never in recommended/security packs.
    if !facts.source_index.has("Intn(4096)") {
        return;
    }

    let start_byte = source.find("Intn(4096)").unwrap_or(0);
    let (line, col) = unit.line_col(start_byte);
    let at = out.len();
    emit::push_finding(
        &META_CWE_334,
        file,
        line,
        col,
        "the generated token comes from a very small 4096-value space and is easy to guess",
        out,
    );
    for f in out.iter_mut().skip(at) {
        f.confidence = Some(0.35); // needle / fixture-shaped
    }
}

pub(crate) fn detect_cwe_335(unit: &ParsedUnit, facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let predictable_seed = (facts.source_index.has("seed := time.Now().Unix()")
        || facts.source_index.has("rand.NewSource(seed)"))
        && (facts.source_index.has("rand.Seed(seed)")
            || facts.source_index.has("rand.New(rand.NewSource(seed))"));
    if !predictable_seed {
        return;
    }

    let start_byte = if let Some(idx) = source.find("time.Now().Unix()") {
        idx
    } else {
        source.find("rand.NewSource(seed)").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_335,
        file,
        line,
        col,
        "the PRNG is seeded from predictable wall-clock time for a security-sensitive ticket value",
        out,
    );
}

pub(crate) fn detect_cwe_338(unit: &ParsedUnit, facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let weak_prng_token = (facts
        .source_index
        .has("rand.New(rand.NewSource(time.Now().UnixNano()))")
        || facts
            .source_index
            .has("rand.NewSource(time.Now().UnixNano())"))
        && (facts.source_index.has("sid") || facts.source_index.has("token"));
    if !weak_prng_token {
        return;
    }

    let start_byte =
        if let Some(idx) = source.find("rand.New(rand.NewSource(time.Now().UnixNano()))") {
            idx
        } else {
            source
                .find("rand.NewSource(time.Now().UnixNano())")
                .unwrap_or(0)
        };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_338,
        file,
        line,
        col,
        "a security-sensitive token is generated from math/rand instead of cryptographic randomness",
        out,
    );
}

pub(crate) fn detect_cwe_342(unit: &ParsedUnit, facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let increments_previous = (facts.source_index.has("lastOTP++")
        && facts.source_index.has("code := lastOTP"))
        || (facts.source_index.has("lastSmsCode++")
            && facts.source_index.has("code := lastSmsCode"));
    if !increments_previous {
        return;
    }

    let start_byte = if let Some(idx) = source.find("lastOTP++") {
        idx
    } else {
        source.find("lastSmsCode++").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_342,
        file,
        line,
        col,
        "the next OTP value is generated by incrementing the previous one",
        out,
    );
}

pub(crate) fn detect_cwe_343(unit: &ParsedUnit, facts: &GoUnitFacts, out: &mut Vec<Finding>) {
    let file = unit.display_path.as_str();
    let source = unit.source.as_ref();

    let deterministic_state_machine =
        facts.source_index.has("*3 + 1) % 97") || facts.source_index.has("*5 + 3) % 101");
    if !deterministic_state_machine {
        return;
    }

    let start_byte = if let Some(idx) = source.find("*3 + 1) % 97") {
        idx
    } else {
        source.find("*5 + 3) % 101").unwrap_or(0)
    };
    let (line, col) = unit.line_col(start_byte);
    emit::push_finding(
        &META_CWE_343,
        file,
        line,
        col,
        "the output range is produced by a deterministic recurrence over shared state and is predictable from previous values",
        out,
    );
}
