//! Shared integration-test helpers.
//!
//! Each integration test binary only uses a subset of these helpers.
#![allow(dead_code)]

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use codehound::engine::Analyzer;
use codehound::fixture::{materialize_fixture, materialize_tree, materialized_root};

pub mod baseline;
pub mod cache;
pub mod inline_ignore;
pub mod manifest;
pub mod reporting;

/// Materialize a `.txt` fixture and verify it parses; does not run the analyzer.
pub fn assert_fixture_materializes(txt_path: &str) -> std::path::PathBuf {
    assert!(
        Path::new(txt_path).is_file(),
        "fixture missing (mandatory .txt): {txt_path}"
    );
    assert!(
        txt_path.ends_with(".txt"),
        "fixtures must use .txt text format, not source extensions: {txt_path}"
    );

    materialize_fixture(Path::new(txt_path))
        .unwrap_or_else(|e| panic!("materialize {txt_path}: {e:#}"))
}

/// Infer the rule class (`"CWE-"` or `"PERF-"`) from the fixture path so the
/// `required_rules == []` branch of `assert_fixture_rules` only enforces
/// silence on the class the test cares about.
fn infer_rule_class(txt_path: &str) -> &'static str {
    if txt_path.contains("/perf/") || txt_path.contains("/perf_real_world/") {
        "PERF-"
    } else if txt_path.contains("/bad_practices/") {
        "BP-"
    } else {
        "CWE-"
    }
}

/// Materialize a `.txt` fixture, analyze it, and assert required rules fired.
pub fn assert_fixture_rules(txt_path: &str, required_rules: &[&str], analyzer: &Analyzer) {
    let source_path = assert_fixture_materializes(txt_path);
    let result = analyzer
        .analyze_paths(&[&source_path], None)
        .unwrap_or_else(|e| panic!("analyze {}: {e:#}", source_path.display()));

    let ids: Vec<&str> = result.findings.iter().map(|f| f.rule_id).collect();
    if required_rules.is_empty() {
        let class = infer_rule_class(txt_path);
        assert!(
            !ids.iter().copied().any(|id| id.starts_with(class)),
            "fixture {txt_path} → {}: expected no {class} findings, got {ids:?}",
            source_path.display()
        );
        return;
    }

    for rule in required_rules {
        assert!(
            ids.contains(rule),
            "fixture {txt_path} → {}: expected rule {rule}, got {ids:?}",
            source_path.display()
        );
    }
}

/// Collect fixture case names from a directory that match the given suffix.
pub fn collect_cases_with_suffix(dir: &Path, suffix: &str) -> BTreeSet<String> {
    let mut cases = BTreeSet::new();

    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let path = entry
            .unwrap_or_else(|e| panic!("read_dir entry {}: {e}", dir.display()))
            .path();
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| panic!("non-utf8 fixture path: {}", path.display()));

        if let Some(case) = name.strip_suffix(suffix) {
            cases.insert(case.to_string());
        }
    }

    cases
}

pub fn unique_temp_root(test_name: &str) -> std::path::PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    std::env::temp_dir().join(format!("codehound-{test_name}-{unique}"))
}

/// Write a Go source file that triggers a command-injection finding.
/// The template uses `w.Write(out)` (not `_, _ = w.Write(out)`) to avoid
/// triggering BP-1 on the final Write call.
pub fn write_go_source(path: &Path, header: &str) {
    let body = r#"// Package sample is generated by integration tests.
package sample

import (
	"net/http"
	"os/exec"
)

func TraceRoute(w http.ResponseWriter, r *http.Request) {
	host := r.URL.Query().Get("host")
	cmd := exec.Command("sh", "-c", "traceroute -m 1 "+host)
	out, err := cmd.CombinedOutput()
	if err != nil {
		http.Error(w, string(out), http.StatusBadRequest)
		return
	}
	w.Write(out)
}
"#;
    let body = body.replacen(
        "func TraceRoute",
        "// TraceRoute executes a shell command with user input.\nfunc TraceRoute",
        1,
    );
    std::fs::write(path, format!("{header}{body}")).unwrap();
}

/// Materialize all `*.{FIXTURE_EXTENSION}` under `fixtures_root`, then scan the generated tree.
pub fn assert_mixed_txt_fixtures(fixtures_root: &str, go_rules: &[&str], python_rules: &[&str]) {
    materialize_tree(Path::new(fixtures_root))
        .unwrap_or_else(|e| panic!("materialize_tree {fixtures_root}: {e:#}"));

    let analyzer = Analyzer::builder().build();
    let result = analyzer
        .analyze_paths(&[materialized_root()], None)
        .unwrap_or_else(|e| panic!("analyze materialized fixtures: {e:#}"));

    let ids: Vec<&str> = result.findings.iter().map(|f| f.rule_id).collect();

    for rule in go_rules {
        assert!(
            ids.contains(rule),
            "mixed materialized scan: expected Go rule {rule}, got {ids:?}"
        );
    }
    for rule in python_rules {
        assert!(
            ids.contains(rule),
            "mixed materialized scan: expected Python rule {rule}, got {ids:?}"
        );
    }
}
